### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by f-w** [bcgov/secure-image-app#7]
Gradle sync error `...\android\keystore.properties (The system cannot find the file specified)`
If the file contains any secret making it unsuitable to share, then pls document what's in the file and how to generate a local one.

**Comment by jleach** [comment]
I can share it internally (bcgov) but not externally. It does not contain anything particularly sensitive besides our Fabric API key; Fabric is now deprecated and this package should be removed from the Android app next time it's being worked on. I've also implemented an automated Android build based on GitHub Actions. Contact me via email for the file.
